{
	"id": "CVE-2018-16438",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2018-16438",
				"description": "An issue was discovered in the HDF HDF5 1.8.20 library. There is an out of bounds read in H5L_extern_query at H5Lexternal.c.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
							"base_score": 6.8,
							"nvd_base_severity": "MEDIUM",
							"temporal_score": 6.8,
							"nvd_temporal_severity": "MEDIUM",
							"environmental_score": 6.8,
							"nvd_environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v30",
						"source": "nvd@nist.gov",
						"cvss_v30": {
							"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
							"base_score": 8.8,
							"base_severity": "HIGH",
							"temporal_score": 8.8,
							"temporal_severity": "HIGH",
							"environmental_score": 8.8,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-125"
						]
					}
				],
				"references": [
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://github.com/TeamSeri0us/pocs/tree/master/hdf5/h5stat"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/TeamSeri0us/pocs/tree/master/hdf5/h5stat"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2018-16438"
					}
				],
				"published": "2018-09-04T00:29:02.293Z",
				"modified": "2024-11-21T03:52:45.347Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "cpe",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"type": "cpe",
																"cpe": "cpe:2.3:a:hdfgroup:hdf5:1.8.20:*:*:*:*:*:*:*"
															}
														}
													}
												]
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2018/CVE-2018-16438.json"
		]
	}
}
