{
	"id": "CVE-2009-5010",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2009-5010",
				"description": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.1 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, a different vulnerability than CVE-2010-3494.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
							"base_score": 4.3,
							"nvd_base_severity": "MEDIUM",
							"temporal_score": 4.3,
							"nvd_temporal_severity": "MEDIUM",
							"environmental_score": 4.3,
							"nvd_environmental_severity": "MEDIUM"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-362"
						]
					}
				],
				"references": [
					{
						"source": "cve@mitre.org",
						"url": "http://bugs.python.org/issue6706"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://code.google.com/p/pyftpdlib/issues/detail?id=91"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://code.google.com/p/pyftpdlib/source/detail?r=439"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn439&r=439&format=side&path=/trunk/pyftpdlib/ftpserver.py"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://www.openwall.com/lists/oss-security/2010/09/09/6"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://www.openwall.com/lists/oss-security/2010/09/11/2"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://www.openwall.com/lists/oss-security/2010/09/22/3"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://www.openwall.com/lists/oss-security/2010/09/24/3"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://bugs.launchpad.net/zodb/+bug/135108"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2009-5010"
					}
				],
				"published": "2010-10-19T20:00:02.957Z",
				"modified": "2010-10-20T04:00:00Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "cpe",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "OR",
												"criterions": [
													{
														"vulnerable": true,
														"fix_status": {
															"class": "unknown"
														},
														"package": {
															"cpe": "cpe:2.3:a:g.rodola:pyftpdlib:*:*:*:*:*:*:*:*"
														},
														"affected": {
															"type": "semver",
															"range": [
																{
																	"le": "0.5.0"
																}
															]
														}
													}
												]
											},
											{
												"operator": "OR",
												"criterions": [
													{
														"vulnerable": true,
														"fix_status": {
															"class": "unknown"
														},
														"package": {
															"cpe": "cpe:2.3:a:g.rodola:pyftpdlib:0.1.1:*:*:*:*:*:*:*"
														}
													}
												]
											},
											{
												"operator": "OR",
												"criterions": [
													{
														"vulnerable": true,
														"fix_status": {
															"class": "unknown"
														},
														"package": {
															"cpe": "cpe:2.3:a:g.rodola:pyftpdlib:0.1:*:*:*:*:*:*:*"
														}
													}
												]
											},
											{
												"operator": "OR",
												"criterions": [
													{
														"vulnerable": true,
														"fix_status": {
															"class": "unknown"
														},
														"package": {
															"cpe": "cpe:2.3:a:g.rodola:pyftpdlib:0.2.0:*:*:*:*:*:*:*"
														}
													}
												]
											},
											{
												"operator": "OR",
												"criterions": [
													{
														"vulnerable": true,
														"fix_status": {
															"class": "unknown"
														},
														"package": {
															"cpe": "cpe:2.3:a:g.rodola:pyftpdlib:0.3.0:*:*:*:*:*:*:*"
														}
													}
												]
											},
											{
												"operator": "OR",
												"criterions": [
													{
														"vulnerable": true,
														"fix_status": {
															"class": "unknown"
														},
														"package": {
															"cpe": "cpe:2.3:a:g.rodola:pyftpdlib:0.4.0:*:*:*:*:*:*:*"
														}
													}
												]
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2009/CVE-2009-5010.json"
		]
	}
}
