{
	"id": "CVE-2022-42731",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2022-42731",
				"description": "mfa/FIDO2.py in django-mfa2 before 2.5.1 and 2.6.x before 2.6.1 allows a replay attack that could be used to register another device for a user. The device registration challenge is not invalidated after usage.",
				"severity": [
					{
						"type": "cvss_v31",
						"source": "nvd@nist.gov",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
							"base_score": 7.5,
							"base_severity": "HIGH",
							"temporal_score": 7.5,
							"temporal_severity": "HIGH",
							"environmental_score": 7.5,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-294"
						]
					}
				],
				"references": [
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/mkalioby/django-mfa2/releases/tag/v2.5.1-release"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/mkalioby/django-mfa2/releases/tag/v2.6.1-release"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2022-42731"
					}
				],
				"published": "2022-10-11T14:15:10.053Z",
				"modified": "2022-10-11T19:05:57.023Z"
			},
			"ecosystems": [
				"cpe"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "cpe",
			"criteria": {
				"operator": "OR",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"package": {
													"cpe": "cpe:2.3:a:django-mfa2_project:django-mfa2:*:*:*:*:*:*:*:*"
												},
												"affected": {
													"type": "semver",
													"range": [
														{
															"lt": "2.5.1"
														}
													]
												}
											}
										]
									},
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"package": {
													"cpe": "cpe:2.3:a:django-mfa2_project:django-mfa2:*:*:*:*:*:*:*:*"
												},
												"affected": {
													"type": "semver",
													"range": [
														{
															"lt": "2.6.1",
															"ge": "2.6.0"
														}
													]
												}
											}
										]
									}
								]
							}
						]
					}
				]
			}
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2022/CVE-2022-42731.json"
		]
	}
}
